// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	rating: {
		/**
		 * g​e​h​t​ ​b​e​s​s​e​r
		 */
		'1': string
		/**
		 * n​i​c​h​t​ ​s​c​h​l​e​c​h​t
		 */
		'2': string
		/**
		 * o​k​a​y
		 */
		'3': string
		/**
		 * g​u​t
		 */
		'4': string
		/**
		 * p​e​r​f​e​k​t​!
		 */
		'5': string
	}
	/**
	 * S​c​h​r​i​t​t​e
	 */
	steps: string
	/**
	 * N​o​c​h​m​a​l​ ​v​e​r​s​u​c​h​e​n
	 */
	try_again: string
}

export type TranslationFunctions = {
	rating: {
		/**
		 * geht besser
		 */
		'1': () => LocalizedString
		/**
		 * nicht schlecht
		 */
		'2': () => LocalizedString
		/**
		 * okay
		 */
		'3': () => LocalizedString
		/**
		 * gut
		 */
		'4': () => LocalizedString
		/**
		 * perfekt!
		 */
		'5': () => LocalizedString
	}
	/**
	 * Schritte
	 */
	steps: () => LocalizedString
	/**
	 * Nochmal versuchen
	 */
	try_again: () => LocalizedString
}

export type Formatters = {}
